bazel_dep(name = "score_ecu_model", version = "0.0.0")
local_path_override(
    module_name = "score_ecu_model",
    path = "..",
)

bazel_dep(name = "rules_python", version = "1.8.5")

# Only required to build the example, shall be replaceable with nearly every other Python toolchain setup
python = use_extension("@rules_python//python/extensions:python.bzl", "python", dev_dependency = True)
python.toolchain(
    python_version = "3.12",
)
