# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: "Build & Test (Host)"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Build all targets
        run: bazel build //...

      - name: Run all tests
        id: run-tests
        run: bazel test //... --build_tests_only

      - name: Upload failed Bazel test logs
        if: inputs.fetch-only != 'true' && failure() && steps.run-tests.outcome == 'failure'
        uses: ./.github/actions/upload_bazel_testlogs_on_failure
        with:
          artifact-name: bazel-testlogs-no-config
